CREATE TABLE IF NOT EXISTS passenger_fcm_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id BIGINT NOT NULL REFERENCES passengers(id),
    fcm_token VARCHAR(512) NOT NULL UNIQUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_passenger_fcm_tokens_passenger
    ON passenger_fcm_tokens (passenger_id);
